name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build
      run: echo "Building application..."

    - name: Copy Files to VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./*"
        target: "/home/azureuser/frozenyogurtshop"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo cp -r /home/azureuser/frozenyogurtshop/* /var/www/html/
          sudo systemctl restart nginx
